## Importing required packages

In [2]:
import pandas as pd
import numpy as np
import seaborn as sn
import matplotlib as mpl
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

## importing the data as pandas dataframe

In [3]:
df1 = pd.read_csv('Data/Placement_Data_Full_Class.csv')


In [4]:
df = df1.copy(deep=True)


## showing top 10 results

In [10]:
df.head(10)


sl_no gender  ssc_p    ssc_b  hsc_p    hsc_b     hsc_s  degree_p  \
0      1      M  67.00   Others  91.00   Others  Commerce     58.00   
1      2      M  79.33  Central  78.33   Others   Science     77.48   
2      3      M  65.00  Central  68.00  Central      Arts     64.00   
3      4      M  56.00  Central  52.00  Central   Science     52.00   
4      5      M  85.80  Central  73.60  Central  Commerce     73.30   
5      6      M  55.00   Others  49.80   Others   Science     67.25   
6      7      F  46.00   Others  49.20   Others  Commerce     79.00   
7      8      M  82.00  Central  64.00  Central   Science     66.00   
8      9      M  73.00  Central  79.00  Central  Commerce     72.00   
9     10      M  58.00  Central  70.00  Central  Commerce     61.00   

    degree_t workex  etest_p specialisation  mba_p      status    salary  
0   Sci&Tech     No    55.00         Mkt&HR  58.80      Placed  270000.0  
1   Sci&Tech    Yes    86.50        Mkt&Fin  66.28      Placed  200000.0  
2  Comm&Mgmt     No    75.00        Mkt&Fin  57.80      Placed  250000.0  
3   Sci&Tech     No    66.00         Mkt&HR  59.43  Not Placed       NaN  
4  Comm&Mgmt     No    96.80        Mkt&Fin  55.50      Placed  425000.0  
5   Sci&Tech    Yes    55.00        Mkt&Fin  51.58  Not Placed       NaN  
6  Comm&Mgmt     No    74.28        Mkt&Fin  53.29  Not Placed       NaN  
7   Sci&Tech    Yes    67.00        Mkt&Fin  62.14      Placed  252000.0  
8  Comm&Mgmt     No    91.34        Mkt&Fin  61.29      Placed  231000.0  
9  Comm&Mgmt     No    54.00        Mkt&Fin  52.21  Not Placed       NaN

# checking for null values 

In [7]:
df.isna().sum()

sl_no              0
gender             0
ssc_p              0
ssc_b              0
hsc_p              0
hsc_b              0
hsc_s              0
degree_p           0
degree_t           0
workex             0
etest_p            0
specialisation     0
mba_p              0
status             0
salary            67
dtype: int64

## shape of the dataset

In [8]:
df.shape


(215, 15)

## check datatypes 

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 215 entries, 0 to 214
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   sl_no           215 non-null    int64  
 1   gender          215 non-null    object 
 2   ssc_p           215 non-null    float64
 3   ssc_b           215 non-null    object 
 4   hsc_p           215 non-null    float64
 5   hsc_b           215 non-null    object 
 6   hsc_s           215 non-null    object 
 7   degree_p        215 non-null    float64
 8   degree_t        215 non-null    object 
 9   workex          215 non-null    object 
 10  etest_p         215 non-null    float64
 11  specialisation  215 non-null    object 
 12  mba_p           215 non-null    float64
 13  status          215 non-null    object 
 14  salary          148 non-null    float64
dtypes: float64(6), int64(1), object(8)
memory usage: 25.3+ KB


## checking number of unique values in each column

In [11]:
df.nunique()

sl_no             215
gender              2
ssc_p             103
ssc_b               2
hsc_p              97
hsc_b               2
hsc_s               3
degree_p           89
degree_t            3
workex              2
etest_p           100
specialisation      2
mba_p             205
status              2
salary             45
dtype: int64

## check statistics of dataset

In [12]:
df.describe()


sl_no       ssc_p       hsc_p    degree_p     etest_p       mba_p  \
count  215.000000  215.000000  215.000000  215.000000  215.000000  215.000000   
mean   108.000000   67.303395   66.333163   66.370186   72.100558   62.278186   
std     62.209324   10.827205   10.897509    7.358743   13.275956    5.833385   
min      1.000000   40.890000   37.000000   50.000000   50.000000   51.210000   
25%     54.500000   60.600000   60.900000   61.000000   60.000000   57.945000   
50%    108.000000   67.000000   65.000000   66.000000   71.000000   62.000000   
75%    161.500000   75.700000   73.000000   72.000000   83.500000   66.255000   
max    215.000000   89.400000   97.700000   91.000000   98.000000   77.890000   

              salary  
count     148.000000  
mean   288655.405405  
std     93457.452420  
min    200000.000000  
25%    240000.000000  
50%    265000.000000  
75%    300000.000000  
max    940000.000000

## insights 

From the above description of numerical data,the average percentages in Secondary Education,Higher Secondary Education and in Degree are very close to each other-between 60.00 to 61.00


# Exploring Data

In [13]:
df.head()

sl_no gender  ssc_p    ssc_b  hsc_p    hsc_b     hsc_s  degree_p  \
0      1      M  67.00   Others  91.00   Others  Commerce     58.00   
1      2      M  79.33  Central  78.33   Others   Science     77.48   
2      3      M  65.00  Central  68.00  Central      Arts     64.00   
3      4      M  56.00  Central  52.00  Central   Science     52.00   
4      5      M  85.80  Central  73.60  Central  Commerce     73.30   

    degree_t workex  etest_p specialisation  mba_p      status    salary  
0   Sci&Tech     No     55.0         Mkt&HR  58.80      Placed  270000.0  
1   Sci&Tech    Yes     86.5        Mkt&Fin  66.28      Placed  200000.0  
2  Comm&Mgmt     No     75.0        Mkt&Fin  57.80      Placed  250000.0  
3   Sci&Tech     No     66.0         Mkt&HR  59.43  Not Placed       NaN  
4  Comm&Mgmt     No     96.8        Mkt&Fin  55.50      Placed  425000.0

In [17]:
print("categories in 'gender' variable:  ",end=" ")
print(df['gender'].unique())
print("categories in 'ssc_b' variable:  ",end=" ")
print(df['ssc_b'].unique())
print("categories in 'hsc_b' variable:  ",end=" ")
print(df['hsc_b'].unique())
print("categories in 'hsc_s' variable:  ",end=" ")
print(df['hsc_s'].unique())
print("categories in 'degree_t' variable:  ",end=" ")
print(df['degree_t'].unique())
print("categories in 'specialisation' variable:  ",end=" ")
print(df['specialisation'].unique())
print("categories in 'status' variable:  ",end=" ")
print(df['status'].unique())

categories in 'gender' variable:   ['M' 'F']
categories in 'ssc_b' variable:   ['Others' 'Central']
categories in 'hsc_b' variable:   ['Others' 'Central']
categories in 'hsc_s' variable:   ['Commerce' 'Science' 'Arts']
categories in 'degree_t' variable:   ['Sci&Tech' 'Comm&Mgmt' 'Others']
categories in 'specialisation' variable:   ['Mkt&HR' 'Mkt&Fin']
categories in 'status' variable:   ['Placed' 'Not Placed']


In [23]:
#define numeric and categorical columns
numeric_columns=[col for col in df.columns if df[col].dtype != '0']
categorical_columns=[col for col in df.columns if df[col].dtype == '']
#print columns
print("we have ",len(numeric_columns)," numerical features:",numeric_columns)
print("we have ",len(categorical_columns)," categorical features:",categorical_columns)


we have  15  numerical features: ['sl_no', 'gender', 'ssc_p', 'ssc_b', 'hsc_p', 'hsc_b', 'hsc_s', 'degree_p', 'degree_t', 'workex', 'etest_p', 'specialisation', 'mba_p', 'status', 'salary']
we have  0  categorical features: []


## Exploring data(Visualization)

In [30]:
df.nunique()


sl_no             215
gender              2
ssc_p             103
ssc_b               2
hsc_p              97
hsc_b               2
hsc_s               3
degree_p           89
degree_t            3
workex              2
etest_p           100
specialisation      2
mba_p             205
status              2
salary             45
dtype: int64